name:                mog
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/lsd-ucsc/mog
license:             BSD3
author:
  - Jonathan Castello <jcaste14@ucsc.edu>
  - Patrick Redmond   <https://recurse.social/@redmp>
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - cryptonite
  - gitlib
  - gitlib-libgit2
  - serialise
  - transformers
  - text
  - filepath
  - directory

ghc-options:
  - -Wall

library:
  source-dirs: src

tests:
  doctest:
    main: Doctests.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - mog
      - doctest
      - QuickCheck
