name:                mog
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/Twisol/mog#readme
license:             BSD3
author:              Jonathan Castello
maintainer:          twisolar@gmail.com
copyright:           Jonathan Castello
category:            Web
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  mog:
    source-dirs:      src
    main:             Main.hs
